services:
  - type: web
    name: gos-wos-mods-forward-any-command
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TWITCH_CHANNEL
        value: xyzgx
      - key: COMANDOS_PERMITIDOS
        value: ""
